import os
from datetime import datetime
import json

def generate_documentation(project, departments, ipv4_plan, vlan_allocations):
    """Generate comprehensive documentation"""
    doc = []
    
    # Header
    doc.append('='*70)
    doc.append('NETRIX - Enterprise Network Design Documentation')
    doc.append('='*70)
    doc.append('')
    doc.append(f'Company: {project.company_name}')
    doc.append(f'Project: {project.name}')
    doc.append(f'Date Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    doc.append(f'Routing Protocol: {project.routing_protocol}')
    doc.append('')
    doc.append('-'*70)
    doc.append('1. NETWORK OVERVIEW')
    doc.append('-'*70)
    doc.append(f'Base Network: {project.base_network}')
    doc.append(f'Total Departments: {len(departments)}')
    total_hosts = sum(dept.hosts for dept in departments)
    doc.append(f'Total Hosts: {total_hosts}')
    doc.append('')
    
    # VLSM Summary
    doc.append('-'*70)
    doc.append('2. VLSM SUBNET ALLOCATION')
    doc.append('-'*70)
    doc.append('')
    doc.append(f'{"Department":<15} {"Hosts":<8} {"Network":<20} {"Mask":<18} {"Prefix":<8} {"Broadcast":<20}')
    doc.append('-'*70)
    for dept in departments:
        doc.append(f'{dept.name:<15} {dept.hosts:<8} {dept.network:<20} {dept.subnet_mask:<18} /{dept.prefix:<7} {dept.broadcast:<20}')
    doc.append('')
    
    # VLAN Table
    doc.append('-'*70)
    doc.append('3. VLAN ALLOCATIONS')
    doc.append('-'*70)
    doc.append('')
    doc.append(f'{"VLAN ID":<10} {"Department":<15} {"Network":<20} {"Ports":<10}')
    doc.append('-'*70)
    for i, vlan in enumerate(vlan_allocations):
        doc.append(f'{vlan["vlan_id"]:<10} {vlan["name"]:<15} {vlan["network"]:<20} {vlan["switch_ports"]:<10}')
    doc.append('')
    
    # IPv4 Plan
    doc.append('-'*70)
    doc.append('4. IPv4 ADDRESSING PLAN')
    doc.append('-'*70)
    doc.append('')
    for dept_name, plan in ipv4_plan.items():
        doc.append(f'Department: {dept_name}')
        doc.append(f'  Gateway: {plan["gateway"]}')
        doc.append(f'  Router Interface: {plan["router_interface"]}')
        doc.append(f'  Switch Management: {plan["switch_management"]}')
        doc.append(f'  PC Range: {plan["pc_range_start"]} - {plan["pc_range_end"]}')
        if plan.get("server_start"):
            doc.append(f'  Server Start: {plan["server_start"]}')
        if plan.get("printer_start"):
            doc.append(f'  Printer Start: {plan["printer_start"]}')
        doc.append('')
    
    # Device Summary
    doc.append('-'*70)
    doc.append('5. DEVICE SUMMARY')
    doc.append('-'*70)
    doc.append('')
    doc.append('Router: R1')
    doc.append('  - Interfaces: ' + ', '.join([f'Gig0/{i}' for i in range(len(departments))]))
    doc.append('  - Routing Protocol: ' + project.routing_protocol)
    doc.append('')
    doc.append('Switch: SW1')
    doc.append('  - VLANs: ' + ', '.join([str(d.vlan_id) for d in departments]))
    doc.append('  - Access Ports: ' + ', '.join([f'Fa0/{i+1}' for i in range(len(departments))]))
    doc.append('  - Trunk Ports: Gig0/1')
    doc.append('')
    
    # Footer
    doc.append('-'*70)
    doc.append('6. DEPLOYMENT CHECKLIST')
    doc.append('-'*70)
    doc.append('')
    doc.append('[ ] Verify all VLANs are configured on switch')
    doc.append('[ ] Verify all IP addresses are configured on router')
    doc.append('[ ] Verify routing protocol is properly configured')
    doc.append('[ ] Verify DHCP pools are configured')
    doc.append('[ ] Test connectivity between all departments')
    doc.append('[ ] Document all configurations')
    doc.append('[ ] Perform security audit')
    doc.append('')
    doc.append('='*70)
    doc.append(f'Documentation generated by NETRIX Framework')
    doc.append('='*70)
    
    return '\n'.join(doc)

def save_report(project_id, doc_content):
    """Save report to file"""
    os.makedirs('reports', exist_ok=True)
    file_path = f'reports/project_{project_id}_report.txt'
    with open(file_path, 'w') as f:
        f.write(doc_content)
    
    # Also generate PDF if reportlab is available
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        
        pdf_path = f'reports/project_{project_id}_report.pdf'
        doc = SimpleDocTemplate(pdf_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Add title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        story.append(Paragraph('NETRIX - Enterprise Network Design Report', title_style))
        story.append(Spacer(1, 0.25*inch))
        
        # Add content
        for line in doc_content.split('\n'):
            if line.strip():
                if line.startswith('='):
                    continue
                elif line.startswith('-'):
                    story.append(Spacer(1, 0.1*inch))
                elif line.startswith('['):
                    story.append(Paragraph(line, styles['Normal']))
                else:
                    story.append(Paragraph(line, styles['Normal']))
            story.append(Spacer(1, 0.05*inch))
        
        doc.build(story)
        return pdf_path
    except:
        return file_path