def generate_switch_config(project, departments):
    """Generate Cisco switch configuration"""
    config = []
    config.append('!')
    config.append(f'! Switch Configuration for {project.company_name}')
    config.append(f'! Generated by NETRIX Framework')
    config.append('!')
    config.append('hostname SW1')
    config.append('!')
    config.append('enable secret cisco')
    config.append('!')
    
    # Create VLANs
    config.append('! VLAN Configuration')
    for dept in departments:
        config.append(f'vlan {dept.vlan_id}')
        config.append(f' name {dept.name}')
        config.append('!')
    
    # Configure access ports
    config.append('! Access Port Configuration')
    for i, dept in enumerate(departments):
        port = f'FastEthernet0/{i+1}'
        config.append(f'interface {port}')
        config.append(f' description {dept.name} Access Port')
        config.append(' switchport mode access')
        config.append(f' switchport access vlan {dept.vlan_id}')
        config.append(' spanning-tree portfast')
        config.append(' no shutdown')
        config.append('!')
    
    # Configure trunk port
    config.append('! Trunk Port Configuration')
    config.append('interface GigabitEthernet0/1')
    config.append(' description Trunk to Router')
    config.append(' switchport mode trunk')
    config.append(' switchport trunk allowed vlan all')
    config.append(' no shutdown')
    config.append('!')
    
    # Configure management interface
    first_dept = departments[0] if departments else None
    config.append('! Management Configuration')
    config.append('interface vlan 1')
    if first_dept:
        mgmt_ip = first_dept.gateway.replace('.1', '.2')
        config.append(f' ip address {mgmt_ip} {first_dept.subnet_mask}')
    else:
        config.append(' ip address 192.168.1.2 255.255.255.0')
    config.append(' no shutdown')
    config.append('!')
    
    config.append('ip default-gateway 192.168.1.1')
    config.append('!')
    config.append('line vty 0 4')
    config.append(' password cisco')
    config.append(' login')
    config.append('!')
    config.append('end')
    
    return '\n'.join(config)