def generate_router_config(project, departments):
    """Generate Cisco router configuration"""
    config = []
    config.append('!')
    config.append(f'! Router Configuration for {project.company_name}')
    config.append(f'! Generated by NETRIX Framework')
    config.append('!')
    config.append('hostname R1')
    config.append('!')
    config.append('enable secret cisco')
    config.append('!')
    
    # Configure interfaces for each department
    for i, dept in enumerate(departments):
        interface = f'GigabitEthernet0/{i}'
        config.append(f'interface {interface}')
        config.append(f' description Connection to {dept.name} VLAN {dept.vlan_id}')
        config.append(f' ip address {dept.gateway} {dept.subnet_mask}')
        config.append(' no shutdown')
        config.append('!')
    
    # Configure routing protocol
    config.append('! Routing Configuration')
    if project.routing_protocol.lower() == 'rip':
        config.append('router rip')
        config.append(' version 2')
        config.append(' no auto-summary')
        for dept in departments:
            network = dept.network
            config.append(f' network {network}')
    elif project.routing_protocol.lower() == 'ospf':
        config.append('router ospf 1')
        config.append(' router-id 1.1.1.1')
        for i, dept in enumerate(departments):
            network = dept.network
            wildcard = calculate_wildcard(dept.subnet_mask)
            config.append(f' network {network} {wildcard} area 0')
    elif project.routing_protocol.lower() == 'eigrp':
        config.append('router eigrp 1')
        config.append(' network 0.0.0.0')
        config.append(' no auto-summary')
    
    config.append('!')
    config.append('! DHCP Configuration')
    config.append('ip dhcp excluded-address 192.168.10.1 192.168.10.10')
    for dept in departments:
        config.append(f'ip dhcp pool {dept.name.lower()}')
        config.append(f' network {dept.network} {dept.subnet_mask}')
        config.append(f' default-router {dept.gateway}')
        config.append(' dns-server 8.8.8.8')
        config.append('!')
    
    config.append('!')
    config.append('line vty 0 4')
    config.append(' password cisco')
    config.append(' login')
    config.append('!')
    config.append('end')
    
    return '\n'.join(config)

def calculate_wildcard(subnet_mask):
    """Calculate wildcard mask from subnet mask"""
    if subnet_mask == '255.255.255.128':
        return '0.0.0.127'
    elif subnet_mask == '255.255.255.192':
        return '0.0.0.63'
    elif subnet_mask == '255.255.255.224':
        return '0.0.0.31'
    elif subnet_mask == '255.255.255.240':
        return '0.0.0.15'
    elif subnet_mask == '255.255.255.248':
        return '0.0.0.7'
    elif subnet_mask == '255.255.255.252':
        return '0.0.0.3'
    else:
        # Calculate wildcard
        import ipaddress
        mask = ipaddress.ip_address(subnet_mask)
        wildcard = int(ipaddress.IPv4Address('255.255.255.255')) ^ int(mask)
        return str(ipaddress.ip_address(wildcard))