from flask import Blueprint, jsonify, request
from flask_login import current_user
from app import db
from app.models import Project, User
from app.services.network_engine import generate_network_data
from app.utils.rbac import (
    login_required_api, permission_required, has_permission
)

api_bp = Blueprint('api', __name__)


@api_bp.route('/health')
def health():
    from app import db
    from flask import current_app
    from sqlalchemy import text
    db_ok = False
    db_error = None
    try:
        db.session.execute(text('SELECT 1'))
        db.session.commit()
        db_ok = True
    except Exception as e:
        db_error = str(e)
    return jsonify({
        'status': 'ok' if db_ok else 'degraded',
        'service': 'NETRIX',
        'version': '1.1.0',
        'rbac': True,
        'database': {
            'connected': db_ok,
            'uri': current_app.config.get('SQLALCHEMY_DATABASE_URI', '')[:80],
            'error': db_error,
        },
    }), (200 if db_ok else 503)


@api_bp.route('/stats')
@permission_required('stats.view')
def stats():
    if has_permission('project.view_all'):
        projects = Project.query.all()
    else:
        projects = Project.query.filter_by(user_id=current_user.id).all()
    total = len(projects)
    completed = sum(1 for p in projects if p.status == 'Completed')
    routers = 0
    validations = 0
    for p in projects:
        if p.generated:
            routers += len(p.generated.get_vlan())
            validations += sum(1 for v in p.generated.get_validation() if v.get('pass'))
    return jsonify({
        'total_projects': total,
        'networks_generated': completed,
        'router_configs': routers,
        'validations': validations,
        'role': current_user.role,
    })


@api_bp.route('/preview-generate', methods=['POST'])
@permission_required('project.generate')
def preview_generate():
    data = request.get_json() or {}
    base = data.get('base_network', '192.168.10.0/24')
    routing = data.get('routing_protocol', 'OSPF')
    router = data.get('router_name', 'R1')
    switch = data.get('switch_name', 'S1')
    depts = data.get('departments', [])
    if not depts:
        return jsonify({'error': 'At least one department required'}), 400
    result = generate_network_data(base, depts, routing, router, switch)
    return jsonify(result)


@api_bp.route('/users/me', methods=['GET', 'PUT'])
@login_required_api
def current_user_profile():
    if request.method == 'GET':
        return jsonify(current_user.to_dict())
    # Self-edit (limited)
    data = request.get_json() or {}
    if 'full_name' in data:
        current_user.full_name = data['full_name']
    if 'email' in data and data['email'] != current_user.email:
        if User.query.filter_by(email=data['email']).first():
            return jsonify({'error': 'Email already in use'}), 409
        current_user.email = data['email']
    if data.get('password'):
        if len(data['password']) < 6:
            return jsonify({'error': 'Password must be at least 6 characters'}), 400
        current_user.set_password(data['password'])
    # Role changes only via admin API
    db.session.commit()
    return jsonify(current_user.to_dict())


@api_bp.route('/permissions')
@login_required_api
def my_permissions():
    return jsonify({
        'role': current_user.role,
        'role_label': current_user.to_dict().get('role_label'),
        'permissions': current_user.permission_list(),
    })


@api_bp.route('/site-config', methods=['GET'])
def site_config():
    """Public frontend config (announcement, branding). No auth required."""
    try:
        from app.models import SiteSetting
        SiteSetting.ensure_defaults()
        s = SiteSetting.all_as_dict()
    except Exception:
        s = {
            'site_name': 'NETRIX',
            'site_tagline': 'Enterprise Network Planning Framework',
            'announcement': '',
            'welcome_message': '',
            'maintenance_mode': 'false',
            'allow_registration': 'true',
            'support_email': '',
            'footer_note': 'Generated by NETRIX',
        }
    return jsonify({
        'site_name': s.get('site_name', 'NETRIX'),
        'site_tagline': s.get('site_tagline', ''),
        'announcement': s.get('announcement', ''),
        'welcome_message': s.get('welcome_message', ''),
        'maintenance_mode': str(s.get('maintenance_mode', 'false')).lower() in ('1', 'true', 'yes'),
        'allow_registration': str(s.get('allow_registration', 'true')).lower() in ('1', 'true', 'yes'),
        'support_email': s.get('support_email', ''),
        'footer_note': s.get('footer_note', ''),
    })
