"""Key-value site settings (admin-managed frontend / system config)."""
from datetime import datetime
from app import db


class SiteSetting(db.Model):
    __tablename__ = 'site_settings'

    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String(80), unique=True, nullable=False, index=True)
    value = db.Column(db.Text, default='')
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    DEFAULTS = {
        'site_name': 'NETRIX',
        'site_tagline': 'Enterprise Network Planning Framework',
        'announcement': '',
        'welcome_message': 'Plan, design and document enterprise networks with VLSM, VLANs and Cisco configs.',
        'maintenance_mode': 'false',
        'allow_registration': 'true',
        'support_email': '',
        'footer_note': 'Generated by NETRIX',
    }

    @classmethod
    def get(cls, key, default=None):
        row = cls.query.filter_by(key=key).first()
        if row is not None:
            return row.value
        if default is not None:
            return default
        return cls.DEFAULTS.get(key, '')

    @classmethod
    def set(cls, key, value):
        row = cls.query.filter_by(key=key).first()
        if not row:
            row = cls(key=key, value=str(value) if value is not None else '')
            db.session.add(row)
        else:
            row.value = str(value) if value is not None else ''
            row.updated_at = datetime.utcnow()
        return row

    @classmethod
    def all_as_dict(cls):
        data = dict(cls.DEFAULTS)
        for row in cls.query.all():
            data[row.key] = row.value
        return data

    @classmethod
    def ensure_defaults(cls):
        for k, v in cls.DEFAULTS.items():
            if not cls.query.filter_by(key=k).first():
                db.session.add(cls(key=k, value=v))
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()
